export const UI_EN = {
  startBtn: 'Start Quiz',
  starting: 'Starting…',
  lblName: 'Full Name *',
  lblSchool: 'School *',
  lblGrade: 'Grade / Index Number (optional)',
  readPhase: 'Read the question',
  answerPhase: 'Choose your answer',
  lockedPhase: 'Answer locked — next question…',
  doneTitle: 'Quiz Submitted',
  doneMsg:
    "Thank you for taking part in DEMETER 26'. Your responses have been recorded. Results of the second round will be announced by the organising committee.",
  autoSubmitTitle: 'Quiz Auto-Submitted',
  autoSubmitMsgPrefix: 'Your quiz was automatically submitted',
  autoSubmitMsgSuffix:
    'If you believe this was a mistake, please contact the quiz coordinators.',
  ruleHeading: 'Before you start:',
  rule1:
    '50 questions. Each question: 10 seconds to read, then 20 seconds to answer — the quiz moves on automatically.',
  rule2:
    'If you answer before the 20 seconds are up, the quiz moves to the next question shortly after — no need to wait out the timer.',
  rule3: "There is no going back once a question's time is up.",
  rule4: 'Answering quickly and correctly can earn you bonus marks.',
  rule5: 'Only one submission per device is allowed.',
  rule6:
    'The quiz runs in full screen. Switching tabs or minimising the window is logged as a violation — 3 violations auto-submit your quiz.',
  rule7:
    'Exiting full screen gives you only 5 seconds to return before your quiz is auto-submitted.',
  rule8:
    'Copying, right-click, and screenshot key combinations are disabled during the quiz.',
  regErrorMissing: 'Please fill in your name and school.',
  lockTitle: 'This device has already been used',
  lockMsg:
    'Only one student may take the quiz per device/browser. If you believe this is an error, please contact the quiz coordinators at your registration desk.',
  fsTitle: 'You exited full screen',
  fsMsg: 'Return to full screen now or your quiz will be auto-submitted.',
  brandSub: 'Second Round — Sinhala Medium',
  brandSubSi: 'දෙවන වටය',
  loading: 'Loading…',
}

export const UI_SI = {
  startBtn: 'ප්‍රශ්නාවලිය ආරම්භ කරන්න',
  starting: 'ආරම්භ වෙමින්…',
  lblName: 'සම්පූර්ණ නම *',
  lblSchool: 'පාසල *',
  lblGrade: 'ශ්‍රේණිය / දර්ශක අංකය (විකල්ප)',
  readPhase: 'ප්‍රශ්නය කියවන්න',
  answerPhase: 'ඔබේ පිළිතුර තෝරන්න',
  lockedPhase: 'පිළිතුර සුරක්ෂිතයි — ඊළඟ ප්‍රශ්නයට…',
  doneTitle: 'ප්‍රශ්නාවලිය ඉදිරිපත් කරන ලදී',
  doneMsg: "DEMETER 26' තරගයට සහභාගී වීම ගැන ඔබට ස්තූතියි. ඔබේ පිළිතුරු සටහන් කර ඇත. දෙවන වටයේ ප්‍රතිඵල සංවිධාන කමිටුව විසින් නිවේදනය කරනු ලැබේ.",
  autoSubmitTitle: 'ප්‍රශ්නාවලිය ස්වයංක්‍රීයව ඉදිරිපත් කරන ලදී',
  autoSubmitMsgPrefix: 'ඔබේ ප්‍රශ්නාවලිය ස්වයංක්‍රීයව ඉදිරිපත් කරන ලදී',
  autoSubmitMsgSuffix: 'මෙය වැරදීමක් යැයි ඔබ සිතන්නේ නම්, කරුණාකර ප්‍රශ්නාවලි සම්බන්ධීකරුවන් අමතන්න.',
  ruleHeading: 'ආරම්භ කිරීමට පෙර:',
  rule1: 'ප්‍රශ්න 50ක්. සෑම ප්‍රශ්නයක්ම: කියවීමට තත්පර 10ක්, පසුව පිළිතුරු දීමට තත්පර 20ක් — ප්‍රශ්නාවලිය ස්වයංක්‍රීයව ඉදිරියට යයි.',
  rule2: 'තත්පර 20 අවසන් වීමට පෙර ඔබ පිළිතුරු දුන්නොත්, ටික වේලාවකින් ප්‍රශ්නාවලිය ඊළඟ ප්‍රශ්නයට යයි — කාලය අවසන් වන තෙක් රැඳී සිටිය යුතු නැත.',
  rule3: 'ප්‍රශ්නයක කාලය අවසන් වූ පසු ආපසු යා නොහැක.',
  rule4: 'වේගයෙන් හා නිවැරදිව පිළිතුරු දීමෙන් ඔබට අමතර ලකුණු ලබා ගත හැක.',
  rule5: 'එක් උපාංගයකට එක් ඉදිරිපත් කිරීමක් පමණක් අවසර ඇත.',
  rule6: 'ප්‍රශ්නාවලිය සම්පූර්ණ තිරයේ ධාවනය වේ. ටැබ් මාරු කිරීම හෝ කවුළුව කුඩා කිරීම උල්ලංඝනයක් ලෙස වාර්තා වේ — උල්ලංඝන 3ක් ඔබේ ප්‍රශ්නාවලිය ස්වයංක්‍රීයව ඉදිරිපත් කරයි.',
  rule7: 'සම්පූර්ණ තිරයෙන් ඉවත් වුවහොත්, ආපසු පැමිණීමට ඔබට තත්පර 5ක් පමණක් ඇත — එසේ නොවුවහොත් ප්‍රශ්නාවලිය ස්වයංක්‍රීයව ඉදිරිපත් වේ.',
  rule8: 'පිටපත් කිරීම, දකුණු-ක්ලික් කිරීම සහ තිර රුව ගැනීමේ යතුරු සංයෝජන ප්‍රශ්නාවලිය අතරතුර අක්‍රීය කර ඇත.',
  regErrorMissing: 'කරුණාකර ඔබේ නම සහ පාසල පුරවන්න.',
  lockTitle: 'මෙම උපාංගය දැනටමත් භාවිතා කර ඇත',
  lockMsg: 'එක් උපාංගයකට/බ්‍රවුසරයකට එක් ශිෂ්‍යයෙකුට පමණක් ප්‍රශ්නාවලියට සහභාගී විය හැක. මෙය වැරදීමක් යැයි සිතන්නේ නම්, ලියාපදිංචි මේසයේ සම්බන්ධීකරුවන් අමතන්න.',
  fsTitle: 'ඔබ සම්පූර්ණ තිරයෙන් ඉවත් විය',
  fsMsg: 'දැන් සම්පූර්ණ තිරයට ආපසු යන්න. එසේ නොවුවහොත් ප්‍රශ්නාවලිය ස්වයංක්‍රීයව ඉදිරිපත් වේ.',
  brandSub: 'දෙවන වටය — සිංහල මාධ්‍යය',
  questionLabel: 'ප්‍රශ්නය',
}
