// DEMETER 26' — Eco Quiz question bank
// NOTE: This file intentionally contains NO correct answers.
// Scoring happens only inside admin.html, which is never shipped to students.
const QUESTION_BANK = [
  { id: 1, q: "When is the World Meteorology Day?", options: ["14th of February", "23rd of March", "23rd of April", "17th May"] },
  { id: 2, q: "How many countries signed the Montreal Protocol?", options: ["127", "187", "177", "197"] },
  { id: 3, q: "The most polluted river in the world, which is the main water resource of Jakarta, Indonesia, is:", options: ["Citarum River", "Meekong River", "Ural River", "Barito River"] },
  { id: 4, q: "Which sea connects the Adriatic Sea to the Mediterranean Sea?", options: ["The North Sea", "Ionian Sea", "The Black Sea", "Aral Sea"] },
  { id: 5, q: "A way that CFC (Chloro Fluoro Carbon) is released to the atmosphere is:", options: ["Using Pesticides", "Using Nuclear Power Plants", "Using Old Refrigerators", "Using Coal Power Plants"] },
  { id: 6, q: "The place where El-Nino happens is:", options: ["The Central and the Eastern equatorial Pacific Ocean", "The Indian Ocean", "The Atlantic Ocean", "The Northern Parts of Pacific Ocean"] },
  { id: 7, q: "What is the global convention made to protect human health and the environment from human-caused mercury releases, and where was it signed?", options: ["Stockholm Convention - Sweden", "Minamata Convention - Japan", "Basel Convention - Switzerland", "Ramsar Convention - Iran"] },
  { id: 8, q: "The pre-historic animal brought back through de-extinction efforts by scientists is:", options: ["The Sabre Toothed Tiger", "Archelon", "Titanaboa", "Dire Wolf"] },
  { id: 9, q: "Who is the national butterfly of Sri Lanka?", options: ["The Common Bird Wing", "The Ceylon Rose", "Ceylon Tree Nymph", "Ceylon Palmfly"] },
  { id: 10, q: "The global biodiversity hotspot located in India is:", options: ["Assam", "Western Ghats", "Hauz Khas District Park", "Kerala"] },
  { id: 11, q: "The main water sources of the Aral Sea and the Dead Sea respectively are:", options: ["Ural and Amur Rivers", "Amu Darya, Syr Darya and the Jordan River", "Yangtze and Meekong Rivers", "The Jordan River and Syr Darya and Amu Darya Rivers"] },
  { id: 12, q: "The deepest point humans have ever explored in the Mariana Trench is:", options: ["Challenger Deep", "Sunda Deep", "Molloy Hole", "Puerto Rico Deep"] },
  { id: 13, q: "How many years does it take to dissolve a toothbrush in a normal environment?", options: ["700 years", "650 years", "600 years", "900 years"] },
  { id: 14, q: "The largest freshwater lake in Asia by land mass, and the country it is located in, respectively:", options: ["Lake Baikal - Russia", "Lake Vular - India", "Lake Balkhash - Kazakhstan", "Lake Qinghai - China"] },
  { id: 15, q: "The largest type of crocodile in the world is:", options: ["The Nile Crocodile", "The Fresh water alligator", "The salt water crocodile", "The American Crocodile"] },
  { id: 16, q: "The hottest city in Asia by temperature is:", options: ["Aden", "Jacobabad", "Madeena", "Dubai"] },
  { id: 17, q: "The pair of rivers that both start from glaciers is:", options: ["Krishnaveni River and Meekong River", "Brahmaputra River and Jordan River", "Citarum River and Kaveri River", "Yamuna River and Ganga River"] },
  { id: 18, q: "The scientific name of the Sri Lankan Leopard is:", options: ["Panthera pardus sinhaleyus", "Panthera tigris lankayeus", "Panthera pardus kotiya", "Panthera leo kotiya"] },
  { id: 19, q: "Walawwatta Wagurana, the only marsh forest in Sri Lanka, is located in:", options: ["Bulathsinhala", "Rathnapura", "Deniyaya", "Bellanwila"] },
  { id: 20, q: "The reason for the movement of tectonic plates in the Earth is:", options: ["Convection Currents", "Geothermal Currents", "Earthquakes", "Air Currents"] },
  { id: 21, q: "What island helped Charles Darwin study the theory of evolution?", options: ["Andaman & Nicobar Islands", "Galapagos Archipelago", "Hawaii", "St. Kitts and Nevis"] },
  { id: 22, q: "What type of tortoise has the longest life expectancy?", options: ["Aldabra Giant Tortoise", "Galapagos Giant Tortoise", "Radiated Tortoise", "Spur-thighed Tortoise"] },
  { id: 23, q: "What type of turtle visits the Sri Lankan coast the most to lay eggs?", options: ["Olive Ridley Turtle", "Leatherback Turtle", "Loggerhead Turtle", "Green Turtle"] },
  { id: 24, q: "The most devastated nuclear power plant explosion in history, with its year, respectively:", options: ["Chernobyl - 1986", "Fukushima Daiichi - 2011", "Three Mile Island - 1979", "Kyshtym - 1957"] },
  { id: 25, q: "The UN Environment Programme evaluated a country for forest fire suppression restoration efforts. Which country?", options: ["Chile", "South Korea", "Canada", "Russia"] },
  { id: 26, q: "What administrative state in the world receives the highest rainfall?", options: ["Cherrapunji", "Kerala", "Mizoram", "Meghalaya"] },
  { id: 27, q: "How many hectares in Sri Lanka are covered with forests?", options: ["1.2 Million Ha", "2.7 Million Ha", "0.8 Million Ha", "1.23 Million Ha"] },
  { id: 28, q: "According to the Red Data Book, which tiger sub-species has only about 30 left?", options: ["Royal Bengal Tiger", "Siberian Tiger", "South China Tiger", "Malayan Tiger"] },
  { id: 29, q: "Who is the closest ancient relative to the Sri Lankan Elephant (Elephas maximus maximus)?", options: ["Elephas maximus maximus", "Paleoloxodon namadicus", "Platybelodon", "Moeritherium"] },
  { id: 30, q: "What sub-species of Asian elephant is critically endangered?", options: ["Sri Lankan Elephant", "Sumatran Elephant", "Indian Elephant", "Javan Elephant"] },
  { id: 31, q: "The largest wetland in Sri Lanka is:", options: ["Bundala", "Kumana", "Anavilundawa", "Muthurajawela"] },
  { id: 32, q: "When was Sri Lanka's Central Environmental Authority established?", options: ["1980", "1982", "1981", "1983"] },
  { id: 33, q: "According to the Air Pollution Index, which country is classified as the most polluted country in the world?", options: ["India", "China", "Pakistan", "Bangladesh"] },
  { id: 34, q: "Where is the sea shore in Sri Lanka most known for pearls?", options: ["Hikkaduwa", "Silavathurai", "Jaffna", "Trincomalee"] },
  { id: 35, q: "What is the project the Indian Government started to save its rivers?", options: ["Jal Shakti Abhiyaan", "Swachh Bharat Abhiyaan", "MISHTI", "Namami Gange"] },
  { id: 36, q: "Which city is known as a 'Ramsar Wetland City'?", options: ["Manila", "Dhaka", "Colombo", "Calcutta"] },
  { id: 37, q: "The largest marshland in the world is:", options: ["Bolivian Pantanal", "Nile Delta", "Sudd", "Okavango"] },
  { id: 38, q: "Which king implemented the 'Maghatha Law', banning the killing of any living organism?", options: ["King Khallatanaga", "King Dutugemunu", "King Mahinda I", "King Amandagamini I"] },
  { id: 39, q: "The two districts where the Bay of Koddiyar and Nandikadal Lagoon are located respectively:", options: ["Mullaitivu and Vavuniya", "Trincomalee and Batticaloa", "Mullaitivu and Trincomalee", "Jaffna and Kilinochchi"] },
  { id: 40, q: "The largest hydro-power plant in Sri Lanka is:", options: ["Victoria", "Polgolla", "Rantambe", "Randenigala"] },
  { id: 41, q: "A mountain range and a river in Pakistan are:", options: ["Hindu Kush and Sulaiman", "Sutlej and Godavari", "Sulaiman and Indus", "Indus and Ghats"] },
  { id: 42, q: "The first farming colony in Sri Lanka is:", options: ["Gal Oya", "Maduru Oya", "Mahaweli", "Kalu Ganga"] },
  { id: 43, q: "The expansion of ATP, and the result of anaerobic respiration, respectively:", options: ["Adenosine Tri Purate", "Adenosine Triple Potash", "Adenosine Tri Pospate", "Adrenosine Tri Pospate"] },
  { id: 44, q: "Ipomea aquatica and Macaca sinica are:", options: ["Water Spinach and Purple Faced Langur", "Spinach and Ceylon Toque Macaque", "Water Spinach and Ceylon Toque Macaque", "Mango and Purple Faced Langur"] },
  { id: 45, q: "Which region experiences high rainfall due to El-Nino?", options: ["South Asia", "East Africa", "Mediterranean Area", "Southeast Asia"] }
];
